"""Add Open Graph, Twitter Card, and canonical URL tags to all HTML pages.

Usage: python tools/add_seo_meta.py
Run from the project root (D:/AIWorkspace/TinloneX.github.io).
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE_URL = "https://tinlone.com"
OG_IMAGE = f"{SITE_URL}/logo.jpg"

# Pages generated by restyle_static_site.py use this exact description format.
# All pages have <meta name="description" content="..."> before the icon link.
META_DESC_MARKER = '<meta name="description" content="'
ICON_MARKER = '<link rel="icon" href="/logo.jpg"'


def compute_url_path(filepath: Path) -> str:
    """Compute site-relative URL path from a file path."""
    rel = str(filepath.relative_to(ROOT)).replace("\\", "/")
    # Handle index.html pages: 2021/04/04/post/index.html -> 2021/04/04/post/
    if rel.endswith("/index.html") or rel == "index.html":
        rel = rel[:-len("index.html")]  # strip "index.html"
    # Ensure it starts with /
    if not rel.startswith("/"):
        rel = "/" + rel
    return rel


def generate_seo_block(og_type: str, title: str, description: str, canonical_url: str) -> str:
    """Generate the OG + Twitter Card + canonical block."""
    # HTML-escape double quotes in content attributes
    esc_title = title.replace('"', '&quot;')
    esc_desc = description.replace('"', '&quot;')
    return (
        f'  <!-- Open Graph -->\n'
        f'  <meta property="og:type" content="{og_type}">\n'
        f'  <meta property="og:title" content="{esc_title}">\n'
        f'  <meta property="og:description" content="{esc_desc}">\n'
        f'  <meta property="og:image" content="{OG_IMAGE}">\n'
        f'  <meta property="og:url" content="{canonical_url}">\n'
        f'  <meta property="og:site_name" content="TinloneX">\n'
        f'  <meta property="og:locale" content="zh_CN">\n'
        f'  <!-- Twitter Card -->\n'
        f'  <meta name="twitter:card" content="summary">\n'
        f'  <meta name="twitter:title" content="{esc_title}">\n'
        f'  <meta name="twitter:description" content="{esc_desc}">\n'
        f'  <meta name="twitter:image" content="{OG_IMAGE}">\n'
        f'  <!-- Canonical -->\n'
        f'  <link rel="canonical" href="{canonical_url}">'
    )


def process_file(filepath: Path) -> bool:
    """Process a single HTML file. Returns True if modified."""
    content = filepath.read_text(encoding="utf-8")

    # Skip files that already have OG tags
    if "og:title" in content:
        return False

    # Determine og_type
    url_path = compute_url_path(filepath)
    og_type = "article" if url_path.startswith("/2021/") else "website"

    # Extract title from <title> tag
    t_start = content.find("<title>")
    t_end = content.find("</title>")
    if t_start >= 0 and t_end > t_start:
        title = content[t_start + 7:t_end]
    else:
        title = "TinloneX"

    # Extract description WITHOUT modifying it
    # The meta description tag has the format:
    #   <meta name="description" content="...">
    d_start = content.find(META_DESC_MARKER)
    if d_start >= 0:
        # Find the closing "> for the meta tag
        tag_content_start = d_start + len(META_DESC_MARKER)
        # The content ends at the next "> (close quote and close tag)
        content_end = content.index('">', tag_content_start)
        description = content[tag_content_start:content_end]
    else:
        description = title

    canonical_url = f"{SITE_URL}{url_path}"
    seo_block = generate_seo_block(og_type, title, description, canonical_url)

    # Insert SEO block AFTER the meta description tag (after the closing >)
    # Find the position right after the meta description closing >
    meta_close_pos = content.index('">', d_start) + 2
    insert_pos = meta_close_pos

    new_content = content[:insert_pos] + "\n" + seo_block + content[insert_pos:]

    if new_content != content:
        filepath.write_text(new_content, encoding="utf-8")
        return True
    return False


def main():
    all_files = sorted(ROOT.rglob("*.html"))
    html_files = [f for f in all_files
                  if os.sep + ".git" + os.sep not in str(f)
                  and os.sep + ".claude" + os.sep not in str(f)]

    print(f"Found {len(html_files)} HTML files to process")
    modified = 0
    skipped = 0

    for fp in html_files:
        try:
            # Skip if already has OG tags
            if "og:title" in fp.read_text(encoding="utf-8"):
                skipped += 1
                continue
            if process_file(fp):
                print(f"  OK {fp.relative_to(ROOT)}")
                modified += 1
        except Exception as e:
            print(f"  ERR {fp.relative_to(ROOT)}: {e}")

    print(f"\nDone. Modified {modified}, skipped {skipped}.")
    print(f"URL prefix: {SITE_URL}")


if __name__ == "__main__":
    main()
